name: CI Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Virtual Environment
        run: make dev-venv

      - name: Linting
        run: make dev-lint

      - name: Unit Tests
        run: make dev-unit-tests
